using System.Numerics;
using Raylib_cs;

/// <summary>Owns every texture: loaded once after the window exists, unloaded once before it closes.</summary>
static class Assets
{
    const int HeroFrameSize = 80;
    const int EnemyFrameSize = 256;
    const int EnemyAttackRows = 3; // side, down, up: ATTACK_ROWS in tools/enemies/make_enemies.py
    // The ultimate's lightning bolt is drawn tall rather than square: one column of sky, one splash on the ground.
    const int UltStrikeFrameWidth = 256;
    const int UltStrikeFrameHeight = 512;

    public static Texture2D Fireball, WelcomBackground, MainMenuBackground; // the stage floor lives in StageMap
    public static SpriteStrip EnemyIdle, EnemyDeath, UltStrike, FireTrail, IceTrail, MagicTrail;
    public static Sound SwordSound, ScoreSound, UltSound, SwordBlockSound;

    public static Color OverlayBlack = new Color(0, 0, 0, 200);
    public static Color OverlayBlack2 = new Color(0, 0, 0, 100);
    // one strip per facing direction, indexed by (int)Direction
    public static SpriteStrip[] HeroIdle = [], HeroWalk = [], HeroRun = [], HeroAxe = [];
    /// <summary>Idle loop, death strip and attack sheets for every look except <see cref="EnemyLook.Sprite"/>; generated by
    /// tools/enemies. A look has a melee sheet, a ranged sheet or both, as its attacks need; the others are null.</summary>
    public static readonly Dictionary<EnemyLook, (SpriteStrip Idle, SpriteStrip Death, SpriteStrip? Melee, SpriteStrip? Ranged)> EnemyArt = [];

    public static void Load()
    {
        WelcomBackground = Raylib.LoadTexture("textures/welcome.png");
        MainMenuBackground = Raylib.LoadTexture("textures/mainmenu.png");
        Fireball = Raylib.LoadTexture("textures/fireball.png");
        EnemyIdle = new(Raylib.LoadTexture("textures/Enemy-Melee-Idle-S.png"), EnemyFrameSize);
        EnemyDeath = new(Raylib.LoadTexture("textures/Enemy-Melee-Death.png"), EnemyFrameSize);
        UltStrike = new(Raylib.LoadTexture("textures/hero/ult-attack/ult_strike.png"), UltStrikeFrameWidth, UltStrikeFrameHeight);
        HeroIdle = LoadHeroStrips("idle/idle");
        HeroWalk = LoadHeroStrips("walk/walk");
        HeroRun = LoadHeroStrips("run/run");
        HeroAxe = LoadHeroStrips("axe attack/axe_attack");
        SwordSound = Raylib.LoadSound("sounds/violent-sword-slice-393848.mp3");
        ScoreSound = Raylib.LoadSound("sounds/level-up-523624.mp3");
        UltSound = Raylib.LoadSound("sounds/ult.mp3");
        SwordBlockSound = Raylib.LoadSound("sounds/sword-block.mp3");
        FireTrail = new(Raylib.LoadTexture("textures/hero/ground-trail-element/fire_trail.png"), 83, 49);
        IceTrail = new(Raylib.LoadTexture("textures/hero/ground-trail-element/ice_trail.png"), 83, 49);
        MagicTrail = new(Raylib.LoadTexture("textures/hero/ground-trail-element/magic_trail.png"), 83, 49);
        foreach (var look in Enum.GetValues<EnemyLook>().Where(l => l != EnemyLook.Sprite))
        {
            string name = $"textures/enemies/{look.ToString().ToLowerInvariant()}";
            EnemyArt[look] = (LoadEnemyArt($"{name}_idle.png"), LoadEnemyArt($"{name}_death.png"),
                LoadAttackSheet($"{name}_melee.png"), LoadAttackSheet($"{name}_ranged.png"));
        }
    }

    public static void Unload()
    {
        Raylib.UnloadTexture(WelcomBackground);
        Raylib.UnloadTexture(MainMenuBackground);
        Raylib.UnloadTexture(Fireball);
        Raylib.UnloadTexture(EnemyIdle.Texture);
        Raylib.UnloadTexture(EnemyDeath.Texture);
        Raylib.UnloadTexture(UltStrike.Texture);
        Raylib.UnloadTexture(FireTrail.Texture);
        Raylib.UnloadTexture(IceTrail.Texture);
        Raylib.UnloadTexture(MagicTrail.Texture);
        foreach (var strip in HeroIdle.Concat(HeroWalk).Concat(HeroRun).Concat(HeroAxe))
            Raylib.UnloadTexture(strip.Texture);
        foreach (var (idle, death, melee, ranged) in EnemyArt.Values)
        {
            Raylib.UnloadTexture(idle.Texture);
            Raylib.UnloadTexture(death.Texture);
            if (melee is { } m) Raylib.UnloadTexture(m.Texture);
            if (ranged is { } r) Raylib.UnloadTexture(r.Texture);
        }
        EnemyArt.Clear();
        Raylib.UnloadSound(SwordSound);
        Raylib.UnloadSound(ScoreSound);
        Raylib.UnloadSound(UltSound);
        Raylib.UnloadSound(SwordBlockSound);
    }

    /// <summary>The enemy art is drawn at 2x world scale and usually shown smaller, so it gets mipmaps and smooth filtering.
    /// Frames are square, so their size comes from the height of a row; each sheet is cropped to fit its own art.</summary>
    static SpriteStrip LoadEnemyArt(string path, int rows = 1)
    {
        var texture = Raylib.LoadTexture(path);
        Raylib.GenTextureMipmaps(ref texture);
        Raylib.SetTextureFilter(texture, TextureFilter.Trilinear);
        return new(texture, texture.Height / rows);
    }

    /// <summary>An attack sheet has a row per direction. A look without that kind of attack has no file, and gets null.</summary>
    static SpriteStrip? LoadAttackSheet(string path) => File.Exists(path) ? LoadEnemyArt(path, EnemyAttackRows) : null;

    static SpriteStrip[] LoadHeroStrips(string basePath)
    {
        string[] suffixes = ["down", "up", "left", "right"]; // same order as the Direction enum
        return suffixes
            .Select(d => new SpriteStrip(Raylib.LoadTexture($"textures/hero/{basePath}_{d}.png"), HeroFrameSize))
            .ToArray();
    }
}
